import { db } from '@/firebaseConfig.js'
import { collection, addDoc } from 'firebase/firestore'

export const seedProductsData = [
  {
    name: 'Smartphone Galaxy S21',
    category: 'Electrónica',
    subcategory: 'oferta',
    stock: 15,
    price: 699,
    description: 'Teléfono inteligente de alta gama',
    image: 'https://placehold.co/300x200?text=Smartphone',
  },
  {
    name: 'Auriculares Inalámbricos',
    category: 'Electrónica',
    subcategory: 'precio normal',
    stock: 50,
    price: 99,
    description: 'Auriculares con cancelación de ruido',
    image: 'https://placehold.co/300x200?text=Auriculares',
  },
  {
    name: 'Camiseta de Algodón',
    category: 'Ropa',
    subcategory: 'precio normal',
    stock: 100,
    price: 20,
    description: 'Camiseta 100% algodón orgánico',
    image: 'https://placehold.co/300x200?text=Camiseta',
  },
  {
    name: 'Chaqueta de Invierno',
    category: 'Ropa',
    subcategory: 'oferta',
    stock: 10,
    price: 120,
    description: 'Chaqueta térmica ideal para el frío',
    image: 'https://placehold.co/300x200?text=Chaqueta',
  },
  {
    name: 'Set de Ollas y Sartenes',
    category: 'Cocina',
    subcategory: 'oferta',
    stock: 25,
    price: 150,
    description: 'Material antiadherente de alta resistencia',
    image: 'https://placehold.co/300x200?text=Cocina',
  },
  {
    name: 'Sofá de 3 Cuerpos',
    category: 'Hogar',
    subcategory: 'precio normal',
    stock: 5,
    price: 500,
    description: 'Sofá cómodo para toda la familia',
    image: 'https://placehold.co/300x200?text=Sofa',
  },
  {
    name: 'Lámpara de Escritorio',
    category: 'Hogar',
    subcategory: 'oferta',
    stock: 30,
    price: 45,
    description: 'Luz LED regulable para escritorio',
    image: 'https://placehold.co/300x200?text=Lampara',
  },
  {
    name: 'Manguera de Riego',
    category: 'Jardín',
    subcategory: 'precio normal',
    stock: 40,
    price: 25,
    description: 'Manguera expandible de 15 metros',
    image: 'https://placehold.co/300x200?text=Manguera',
  },
  {
    name: 'Pala de Jardinería',
    category: 'Jardín',
    subcategory: 'oferta',
    stock: 80,
    price: 15,
    description: 'Pala de metal resistente para mover tierra',
    image: 'https://placehold.co/300x200?text=Pala',
  },
  {
    name: 'Licuadora Profesional',
    category: 'Cocina',
    subcategory: 'precio normal',
    stock: 20,
    price: 90,
    description: 'Licuadora de 1000W con vaso de vidrio',
    image: 'https://placehold.co/300x200?text=Licuadora',
  },
  {
    name: 'Smart TV 55 Pulgadas',
    category: 'Electrónica',
    subcategory: 'oferta',
    stock: 8,
    price: 450,
    description: 'Televisor 4K UHD con control por voz',
    image: 'https://placehold.co/300x200?text=Smart+TV',
  },
  {
    name: 'Reloj Inteligente',
    category: 'Electrónica',
    subcategory: 'precio normal',
    stock: 35,
    price: 150,
    description: 'Monitor de ritmo cardíaco y notificaciones',
    image: 'https://placehold.co/300x200?text=Reloj',
  },
  {
    name: 'Pantalón Vaquero',
    category: 'Ropa',
    subcategory: 'precio normal',
    stock: 60,
    price: 40,
    description: 'Jeans de corte recto y tela elástica',
    image: 'https://placehold.co/300x200?text=Pantalón',
  },
  {
    name: 'Zapatillas Deportivas',
    category: 'Ropa',
    subcategory: 'oferta',
    stock: 25,
    price: 80,
    description: 'Calzado ligero para correr larga distancia',
    image: 'https://placehold.co/300x200?text=Zapatillas',
  },
  {
    name: 'Cafetera de Cápsulas',
    category: 'Cocina',
    subcategory: 'precio normal',
    stock: 12,
    price: 110,
    description: 'Prepara espresso y lattes en segundos',
    image: 'https://placehold.co/300x200?text=Cafetera',
  },
  {
    name: 'Batidora de Mano',
    category: 'Cocina',
    subcategory: 'oferta',
    stock: 40,
    price: 35,
    description: 'Incluye accesorios para picar y batir',
    image: 'https://placehold.co/300x200?text=Batidora',
  },
  {
    name: 'Mesa de Centro',
    category: 'Hogar',
    subcategory: 'precio normal',
    stock: 15,
    price: 180,
    description: 'Mesa de madera estilo rústico',
    image: 'https://placehold.co/300x200?text=Mesa',
  },
  {
    name: 'Cortinas Opacas',
    category: 'Hogar',
    subcategory: 'oferta',
    stock: 50,
    price: 55,
    description: 'Bloquean el 99% de la luz solar',
    image: 'https://placehold.co/300x200?text=Cortinas',
  },
  {
    name: 'Maceta de Cerámica',
    category: 'Jardín',
    subcategory: 'precio normal',
    stock: 70,
    price: 20,
    description: 'Ideal para plantas de interior',
    image: 'https://placehold.co/300x200?text=Maceta',
  },
  {
    name: 'Tijeras de Podar',
    category: 'Jardín',
    subcategory: 'oferta',
    stock: 45,
    price: 18,
    description: 'Corte preciso para ramas gruesas',
    image: 'https://placehold.co/300x200?text=Tijeras',
  },
]

export async function seedDatabase() {
  const promises = seedProductsData.map(async (prod) => {
    return await addDoc(collection(db, 'products'), prod)
  })
  await Promise.all(promises)
  console.log(`${seedProductsData.length} products seeded successfully`)
}
